fix: belongs_to link inside tabs
avo-hq/avo pull request #1242
Opened 2022-09-17 11:10 UTC by Paul-Bob

# Description

Fixes https://github.com/avo-hq/avo/issues/1194

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/docs)
- [ ] I have added tests that prove my fix is effective or that my feature works

2022-09-26 09:41 UTC, adrianthedev commented
I pushed some changes for the comment resource. It doesn't work for me there. Does it work for you?

Also, can we add tests for that please?

2022-09-26 09:42 UTC, adrianthedev requested changes
It doesn't work for me on the comment resource. Does it work for you?

Can we also add tests please?

2022-10-08 10:27 UTC, Paul-Bob commented
> It doesn't work for me on the comment resource. Does it work for you?
> 
> Can we also add tests please?

@adrianthedev panel items fixed. I moved the comments fields back because some specs are dependent on them. We can do a system test for this, do you agree?

2022-10-09 15:02 UTC, adrianthedev approved these changes
I'm wondering if we still need a piece of code. Otherwise it's pretty much ready to merge

2022-10-09 16:45 UTC, Paul-Bob commented on lib/avo/fields/belongs_to_field.rb
> +      attr_accessor :inside_tab
You mean using `target` and give it `_top` when inside a panel or a tab?

2022-10-09 16:46 UTC, adrianthedev commented on lib/avo/fields/belongs_to_field.rb
> +      attr_accessor :inside_tab
Yes! And `nil` by default.

2022-10-09 16:48 UTC, Paul-Bob commented on lib/avo/fields/belongs_to_field.rb
> +      attr_accessor :inside_tab
Sure, that's actually a great suggestion to simplify our problem, when i choose `inside_tab` name I was thinking about the possibility of reusing that boolean for some other contexts but for now we don't need that so I agree on keep it simple ;)

2022-10-09 16:49 UTC, Paul-Bob commented on lib/avo/concerns/has_fields.rb
> +        panelfull_items.grep(Avo::TabGroup).each do |tab_group|
Always learning! =))

2022-10-09 16:53 UTC, Paul-Bob commented on lib/avo/tab_group_builder.rb
> +    parsed = Avo::Dsl::FieldParser.new(id: field_name, order_index: @items_index, **args.merge(inside_tab: true), &block).parse
I think we don't, great observation

2022-10-09 17:03 UTC, merged