wip
avo-hq/avo pull request #182
Opened 2020-11-06 11:06 UTC by mihaimdm22

Run command for generation of resource and model: `rails generate avo:resource Book --fields name:text year:integer likes:object description:text `.
Run command for generation of resource only:`rails generate avo:resource Book --fields name:text year:integer likes:object description:text --generate_model false`.

Looking also into generation of resource when running `rails generate model Book name:text ...`

2020-11-13 11:17 UTC, adrianthedev requested changes
Some notes:

- we can get the attachment/attachments through `model.reflections`
- we can get the relationships trhough `model.reflections`
- ignore some fields:
  - default timestamps `created_at`, `updated_at`
  - from devise `reset_password_sent_at`, `remember_created_at`, `reset_password_token`


On `rails g avo:resource User --generate-fields --model_class Admin::User` I get an extra space.

![image](https://user-images.githubusercontent.com/1334409/99062950-6e4bdc00-25ac-11eb-9f6d-9a325731f103.png)

Same on `rails g avo:resource User --generate-fields`

![image](https://user-images.githubusercontent.com/1334409/99063104-aeab5a00-25ac-11eb-8a17-12d5422d961f.png)

2020-11-13 11:17 UTC, adrianthedev commented on lib/generators/avo/resource_generator.rb
> +        stage: {
IDK if we should generate this as a select. no options given.

We can use `models.defined_enums` to get all the enums ans set them as a select with `enum` option.
ex: `select :stage, enum: ::Project.stages`

2020-11-13 11:17 UTC, adrianthedev commented on lib/generators/avo/resource_generator.rb
> +        id: {
We can have a `country` field.

```suggestion
		country: {
			field: 'country',
		},
        id: {
```

2020-11-13 11:17 UTC, adrianthedev commented on lib/generators/avo/resource_generator.rb
> +        model.columns_hash.each { |k, v| columns_with_type[k] = v.type }
```suggestion
        columns_with_type = model.columns_hash.map { |k, v| [columns_with_type[k], v.type] }.to_h
```

2020-11-13 11:17 UTC, adrianthedev commented on lib/generators/avo/resource_generator.rb
> +      if !columns_with_type.empty?
```suggestion
      if columns_with_type.present?
```

2020-11-13 11:17 UTC, adrianthedev commented on lib/generators/avo/resource_generator.rb
> +        columns_with_type.each do |fieldname, fieldtype|
They are two words.
```suggestion
        columns_with_type.each do |field_name, field_type|
```

2020-11-16 10:28 UTC, mihaimdm22 commented on lib/generators/avo/resource_generator.rb
> +        model.columns_hash.each { |k, v| columns_with_type[k] = v.type }
doesn't work this way

2021-04-01 15:20 UTC, closed without merging

2022-01-08 18:50 UTC, IrvanFza commented
Hi @mihaimdm22 @adrianthedev, just wondering if this feature will be implemented on Avo any time soon. Really love your work on Avo, and probably will become the game-changer on Rails admin dashboard-related gem. This feature will make Avo more awesome!

2022-01-11 13:41 UTC, adrianthedev commented
Hey @IrvanFza 
We don't have the capacity to tackle this feature now, but we're more than open if someone would like to take this PR over. We're pretty supportive of our contributors and help them navigate the codebase.