feature: added a preview when editing/creating images, video or audio
avo-hq/avo pull request #2438
Opened 2024-02-01 05:55 UTC by maxencehenneron

# Description

It adds a preview when adding and image/video/audio to a "file" field.

Note: a preview already exists when the record is created, but does not automatically update when you select another file. While my code works, I don't think it's the cleanest.

Some logic is duplicated between edit_component.html.erb (file field) and grid_item_component.html.erb.
grid_item_component references file_field_controller and I don't know if it's a bad practice. 

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

https://github.com/avo-hq/avo/assets/377682/f6d3cc4c-cfac-4595-b4a8-d967b52f122f

2024-02-05 11:32 UTC, adrianthedev requested changes
This is a great start @maxencehenneron. Thanks!

I left a comment to remove a bit of duplication.
Usually, I'm not afraid of duplication, but this is not the right place IMHO. We'll forget it's in two places.

If you can help address that, it'll be pretty good to merge

2024-02-05 11:32 UTC, adrianthedev commented on app/components/avo/fields/file_field/edit_component.html.erb
> +        <%= video_tag("", "data-file-field-target": "preview", controls: true, preload: false, class: 'w-full') %>
I don't think it's a good idea to have this duplication here.
The first time someone updates one tag here or in `GridItemComponent`, the other one will not be updated.

Can we try to use only `GridItemComponent`?

2024-02-05 11:32 UTC, adrianthedev commented on app/components/avo/fields/file_field/edit_component.html.erb
>      <div class="mb-2">
Can we add the `mb-2` class inside that parent `div` so we won't have two nested divs?

2024-02-05 11:32 UTC, adrianthedev commented on app/javascript/js/controllers/fields/file_field_controller.js
> +      this.previewTarget.src = reader.result
Let's do a check to see if the target is present.

2024-02-27 04:12 UTC, adrianthedev commented
@maxencehenneron are you able to move this past the finish line?

2024-03-04 23:28 UTC, maxencehenneron commented
> @maxencehenneron are you able to move this past the finish line?

Sorry I don't have much time to complete this, I don't see any simple way to achieve this without significant refactoring as we do not have a file yet when first creating the object

2024-04-04 01:57 UTC, closed without merging