feature: `association` option for association fields
avo-hq/avo pull request #2560
Opened 2024-03-05 12:49 UTC by Paul-Bob

# Description

Fixes #2559

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

2024-03-08 07:44 UTC, Paul-Bob commented
TODO:

- [ ] docs
- [ ] tests
- [ ] fix select all issue where it selects all from both tables

2024-03-15 14:59 UTC, adrianthedev commented
Let's wait on this.
I have an idea of a `for_column` or `for_field` (open to better naming) which should do the same thins as `association` but for any field.

```ruby
field :full_name, as: :text, for_field: :name, format_using: -> {something}
field :super_name, as: :text, for_field: :name, format_using: -> {something_else}
```

Do you think we need something like that?

2024-03-15 15:24 UTC, Paul-Bob commented
> Let's wait on this. I have an idea of a `for_column` or `for_field` (open to better naming) which should do the same thins as `association` but for any field.
> 
> ```ruby
> field :full_name, as: :text, for_field: :name, format_using: -> {something}
> field :super_name, as: :text, for_field: :name, format_using: -> {something_else}
> ```
> 
> Do you think we need something like that?

`for_field` option aims to the model attribute? I.E. both fields on your example will fetch the value from `record.name`?

If i understand it right I think that's interesting and is like renaming and extending the `association` option to all fields :ok_hand: 

This opens another suggestion, a way to directly pass the value similar like the field block but applied to all views

```ruby
field :full_name, as: :text, value: -> { record.name }, format_using: -> {something}
field :super_name, as: :text, value: -> { record.name }, format_using: -> {something_else}
```

Lets keep an eye on this PR since some logic might be reused whatever approach we follow.

2024-03-15 15:25 UTC, Paul-Bob commented
Actually with the `value: -> { record.name }` suggestion there is no need to format, is like `for_field` + `format_using` in one option

2024-04-12 10:17 UTC, adrianthedev commented
Let's create a PoC for this and name it `for_attribute` or `as_attribute`.

2024-04-12 10:18 UTC, adrianthedev requested changes
Letf a comment.

2024-04-18 09:37 UTC, merged