fix: preserve page when go back from resource show page (#1555)
avo-hq/avo pull request #2652
Opened 2024-04-01 19:21 UTC by dmitrytrager

# Description

Preserve page number when going back from resource show page.
Page number is fetched from referral url by parsing its query params.

Another approach can be using pagination data from index page as a parameter for generated links and then just checking `params` for `back_path`. The problem with this option is not that we will have to pass `@pagy` down through components tree, but that page number will be present in show links as well, which seems redundant.

Fixes [#1555](https://github.com/orgs/avo-hq/projects/8?pane=issue&itemId=47768610)

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [x] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

## Manual review steps

1. Run local dummy app
2. Open project list and go to page 2
3. Select some project and open show page
4. Click 'Go back'
5. Make sure you are on page 2 

Manual reviewer: please leave a comment with output from the test if that's the case.

2024-04-06 14:42 UTC, dmitrytrager commented
Updated code style here a bit

2024-04-09 10:17 UTC, Paul-Bob requested changes
Thanks for the initiative @dmitrytrager is a great beginning!

Let's refactor it a little bit and apply the same logic when editing.

I was thinking about a private method inside `Avo::ResourceComponent` class:
```ruby
  def referrer_params
    {
      page: referrer_params["page"]
    }.compact
  end
```

This way we can apply it to all needed paths like `**referrer_params`. Since we compact the `referrer_params` that means `nil` values will be erased from the hash and we do no longer need the `via_page?` method and verification.

We can now apply this strategy:
```ruby
# app/components/avo/views/resource_edit_component.rb
# Line 26
return helpers.resource_path(record: @resource.record, resource: @resource, **referer_params)

# Line 33
helpers.resources_path(resource: @resource, **referer_params)
```

Inside `app/components/avo/views/resource_show_component.rb` file we can replace 

```ruby
via_page? ?
        helpers.resources_path(resource: @resource, page: referrer_params["page"]) :
        helpers.resources_path(resource: @resource)
```

By:

```ruby
helpers.resources_path(resource: @resource, **referer_params)
```

Thanks again for looking into it!

2024-04-12 09:12 UTC, Paul-Bob approved these changes
Thank you @dmitrytrager !

2024-04-12 10:40 UTC, adrianthedev commented on app/components/avo/resource_component.rb
> +    { page: referrer_params["page"] }.compact
```suggestion
    {page: referrer_params["page"]}.compact
```

2024-04-12 10:43 UTC, adrianthedev approved these changes

2024-04-12 10:43 UTC, merged