Create button to nullify date_time fields
avo-hq/avo pull request #2951
Opened 2024-07-06 10:54 UTC by binarygit

# Description
This PR adds a button to nullify date_time fields.

Fixes #2770

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording
This is how it looks right now:

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

2024-07-06 11:01 UTC, binarygit commented
I haven't found a good way to align the button horizontally to the input field. I poked around the css but no luck.

My approach is to add the button inside the `app/components/avo/field_wrapper_component.html.erb` and then render it conditionally. However I don't think it's a good idea which is why I wanted to ask you guys if you see/know an easier way to have the button render horizontal to the input field.

2024-07-07 13:47 UTC, binarygit commented
Tests pass locally. Not sure why CI's fails :shrug:

2024-07-08 11:34 UTC, adrianthedev commented
What do you think about this type of button @binarygit?

![CleanShot 2024-07-08 at 14 32 45](https://github.com/avo-hq/avo/assets/1334409/baa5fa98-f379-4089-9d0f-9ebbd36ed381)

2024-07-08 13:18 UTC, adrianthedev commented
The linter is [failing](https://github.com/avo-hq/avo/actions/runs/9840142380/job/27163697899?pr=2951#step:12:54), and with my suggestion as well. Let's lowercase the `reset` translation, please.

2024-07-08 13:25 UTC, binarygit commented
It's done

2024-07-08 15:35 UTC, adrianthedev requested changes
It's almost done to merge.
We need to apply the changes to the other field as well.

2024-07-15 06:05 UTC, binarygit commented on app/components/avo/fields/time_field/edit_component.html.erb
> +      <%= render Avo::Fields::Common::BooleanCheckComponent.new %>
This comment completely flew under my radar! I have just made the requested change.

2024-07-15 07:49 UTC, merged