[#2996] - Change boolean field to show dash when null
avo-hq/avo pull request #2997
Opened 2024-07-16 20:51 UTC by serene

# Description

Fixes # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

2024-07-17 07:57 UTC, Paul-Bob requested changes
Hei @serene thanks for looking into this! It's looking good

Since the default value for `dash_if_blank` is `true` ([source code](https://github.com/avo-hq/avo/blob/fix/policies/app/components/avo/field_wrapper_component.rb#L15))let's remove it from the arguments. 

Otherwise, it's good to go!

2024-07-17 07:57 UTC, Paul-Bob commented on app/components/avo/fields/boolean_field/index_component.html.erb
> +<%= index_field_wrapper **field_wrapper_args, dash_if_blank: true, flush: true do %>
```suggestion
<%= index_field_wrapper **field_wrapper_args, flush: true do %>
```

2024-07-17 07:57 UTC, Paul-Bob commented on app/components/avo/fields/boolean_field/show_component.html.erb
> +<%= field_wrapper **field_wrapper_args, dash_if_blank: true do %>
```suggestion
<%= field_wrapper **field_wrapper_args do %>
```

2024-07-17 09:02 UTC, Paul-Bob approved these changes
Since the changes from the last review were minor, I went ahead and applied them to merge this PR

Thank you @serene!

2024-07-17 09:02 UTC, merged

2024-07-17 18:05 UTC, donnyli95 commented
Hey @Paul-Bob, is this going to be released in avo 3.10.7? When will that be released? I've tried pointing to the main avo branch for now to be able to use the nullable dash but `bundle exec rake avo:sym_link` doesn't seem to work since it also depends on the avo-pro gem. 

My gemfile setup looks like:
```
gem 'avo', github: 'avo-hq/avo', branch: 'main'
gem "avo-pro", ">= 3.10.6", source: "https://packager.dev/avo-hq/"
```

and `bundle exec rake avo:sym_link` results in a `[Avo->] Failed to find avo.base.css.` error

2024-07-17 21:28 UTC, Paul-Bob commented
Hello, yes, it will be available on the next release, 3.10.7, can't say when since we do not have exact dates for patch releases, only for minor ones that are always on the first Tuesday of the month.

We will investigate the error that you're experiencing.

I normally don't encourage monkey patching, but in this case, since it's a minor change, you can eject (https://docs.avohq.io/3.0/eject-views.html#field_components) the affected components and apply the changes on th3 ejected ones. If you do so, make sure to remove the monkey patch after the official release.

2024-07-22 20:29 UTC, donnyli95 commented
@Paul-Bob I've just pushed my app with the latest avo update 3.10.7 and noticed that the false values for the boolean fields are also coming out as dashes. 

For example if i write: 
```
field 'cheese', as: :boolean, do
  false
end
```

this comes out as a dash instead of the original red X. Just wanted to confirm if you've also noticed this issue or not?

2024-07-22 20:42 UTC, Paul-Bob commented
You're right @donnyli95 I'll have a look.

2024-07-24 12:57 UTC, Paul-Bob commented
@donnyli95 just letting you know that it has been fixed since version 3.10.8