Call destroy when detaching through associations
avo-hq/avo pull request #3004
Opened 2024-07-17 18:56 UTC by binarygit

# Description

Fixes # (issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

2024-07-17 19:08 UTC, binarygit commented
@Paul-Bob 
```
# team.rb
  has_many :team_members, through: :memberships, class_name: "User", source: :user, inverse_of: :teams

# user.rb
  has_and_belongs_to_many :teams, join_table: :team_memberships, inverse_of: :admin
```

Here team defines it's team_members assoc using a through table however, User defines the same association as a HABTM.

Detaching a user from the team show page will call `team_membership.destroy` but because user has setup this assoc as HABTM I don't think when detaching a team from the user's show page should call `team_membership.destroy`. Am I correct?

2024-07-19 17:56 UTC, Paul-Bob commented
> Update: Adrian and I talked about this. user.rb should be declaring the relationship as a through relationship. It's unusual to declare a relationship as a through at one end and a HABTM on the other end.

Agree, I also noticed that particularity on our dummy recently. 

Does this PR work well from both sides if the associations are correctly defined?

2024-07-23 08:31 UTC, binarygit commented on spec/features/avo/has_many_field_spec.rb
> +    it "triggers callbacks when called from the other model too" do
Yes it works both ways of the association @Paul-Bob. This test verifies that :sweat_smile:

2024-07-25 12:05 UTC, Paul-Bob commented on spec/dummy/app/models/user.rb
> +  has_many :team_memberships
```suggestion
```

Same association already defined (L39)

2024-07-25 12:06 UTC, Paul-Bob requested changes
Looking good! Thanks @binarygit, let's please remove the duplicated association and also solve the conflicts.

2024-07-25 12:07 UTC, binarygit commented
Wait. I’m working on displaying the messages when associations are misconfigured

2024-07-25 14:19 UTC, binarygit commented on spec/dummy/app/models/user.rb
> +  has_many :team_memberships
Thanks. I didn't notice this!

2024-07-25 16:56 UTC, binarygit commented
@Paul-Bob I couldn't find a straightforward way to check if associations are properly configured. Sorry for holding this up, maybe merge this now and I'll pick this up again later.

2024-07-25 17:41 UTC, binarygit commented
I actually talked about this here: https://rubyonrails-link.slack.com/archives/C05054QPL/p1721928807967489 and I don't think verifying associations are setup correctly should be our job. 

I did try and it's too much work and also feels like it should be upto the user (like the devs point out in the link) to set it up correctly.

2024-07-25 18:15 UTC, Paul-Bob commented
It's ok without the association check @binarygit thanks for looking into it

2024-07-26 06:50 UTC, adrianthedev approved these changes
Looks good.

2024-07-27 07:59 UTC, Paul-Bob approved these changes
It's looking good, thanks @binarygit!

2024-07-27 08:00 UTC, merged