Feature: Add breadcrumbs to association pages
avo-hq/avo pull request #3082
Opened 2024-08-01 19:13 UTC by binarygit

- Show breadcrumbs when association pages are opened directly
- Refactor: create helper

# Description

Fixes # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

## Manual review steps

1. Step 1
1. Step 2

Manual reviewer: please leave a comment with output from the test if that's the case.

2024-08-02 10:45 UTC, Paul-Bob requested changes
Association tables are broken when loading [a team page](http://localhost:3030/admin/resources/teams/3)

Also lets ensure tests are passing

2024-08-06 06:46 UTC, adrianthedev requested changes
Let's undo the `@turbo_frame` and remove `html_req_for_association_page?`

2024-08-06 08:13 UTC, adrianthedev commented on app/controllers/avo/base_controller.rb
> +      if @reflection.present? && !helpers.turbo_frame_request?
do we need `helpers.` here?

2024-08-06 08:15 UTC, binarygit commented on app/controllers/avo/base_controller.rb
> +      if @reflection.present? && !helpers.turbo_frame_request?
Ah! sorry I missed it.

2024-08-06 08:16 UTC, Paul-Bob requested changes

2024-08-06 08:16 UTC, Paul-Bob commented on app/components/avo/views/resource_index_component.html.erb
> +      display_breadcrumbs: @reflection.present? && !helpers.turbo_frame_request?
```suggestion
      display_breadcrumbs: @reflection.blank? || (@reflection.present? && !helpers.turbo_frame_request?)
```

2024-08-06 08:16 UTC, adrianthedev commented on spec/features/avo/breadcrumbs_spec.rb
> +      url = "/admin/resources/users/#{user.slug}/teams?view=show&turbo_frame=has_and_belongs_to_many_field_show_teams"
```suggestion
      url = "/admin/resources/users/#{user.slug}/teams?view=show"
```

2024-08-06 08:22 UTC, binarygit commented on spec/features/avo/breadcrumbs_spec.rb
> +      url = "/admin/resources/users/#{user.slug}/teams?view=show&turbo_frame=has_and_belongs_to_many_field_show_teams"
Done

2024-08-06 08:41 UTC, merged