refactor: replace OpenStruct with Data for performance and readability improvement
avo-hq/avo pull request #3307
Opened 2024-10-04 10:22 UTC by Yash-Singh-Pathania

# Description

This PR refactors the codebase by replacing `OpenStruct` with `Data` for improved performance and immutability. The change ensures that `Data` is used to represent immutable objects, which provides better memory usage and execution speed compared to `OpenStruct`. No additional dependencies are required for this change.

Fixes # (issue)
[#3245](https://github.com/avo-hq/avo/issues/3245)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the [documentation](https://github.com/avo-hq/avodocs)
- [ ] I have added tests that prove my fix is effective or that my feature works

## Screenshots & recording

N/A (No UI changes involved)

## Manual review steps

1. Verify that the `accounts` method returns the correct objects using the new `Data` class.
2. Ensure that `perform_request` correctly handles the refactored `Response` class in test mode.

Manual reviewer: please leave a comment with output from the test if that's the case.

2024-10-04 10:48 UTC, adrianthedev commented on docs.avohq.io
I dont' think this should be here.
This is why the CI is failing.

2024-10-14 15:25 UTC, Yash-Singh-Pathania commented
@adrianthedev  can you please  review this , I think its done sorry for the delay I just got started with my masters 
thanks a ton.

2024-10-21 11:31 UTC, Yash-Singh-Pathania commented
@Paul-Bob  would you be reviewing this ?

2024-10-21 12:03 UTC, Paul-Bob requested changes
It feels unnatural to create a new class and override the initializer; it seems like we're not using the right tool for the job.

I came across this article discussing alternatives to `OpenStruct`:
https://dev.to/lorankloeze/alternative-for-rubys-openstruct-i72

I think we should consider using a more appropriate tool, such as `Struct` or `Data`.

`Struct` is significantly faster than `OpenStruct` (~80 times faster), although I’m unsure how it compares to `Data`. Let’s either research or run a quick benchmark, similar to the one in the article, to determine which option `Struct` or `Data` is faster, and proceed with that.

2024-10-21 12:05 UTC, Yash-Singh-Pathania commented
@Paul-Bob  let me go through this quickly and run a quick benchmark for the same.

2024-11-01 11:40 UTC, Paul-Bob commented on spec/dummy/app/models/user.rb
> +
```suggestion
```

2024-11-01 11:52 UTC, Paul-Bob approved these changes
Thank you for working on this @Yash-Singh-Pathania 

I've completed the PR by using `Struct` instead of previous approaches.

2024-11-01 11:53 UTC, merged